import type { Metadata } from "next";
import "./globals.css";
import "./generated.css";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import QueryProvider from "@/providers/QueryProvider";

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const locale = await getLocale();

	return (
		<html lang={locale}>
			<body className={`mx-auto`}>
				<NextIntlClientProvider>
					<QueryProvider>{children}</QueryProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
