name: Build

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-24.04

        services:
            postgres:
                image: postgres:15
                ports:
                    - 5432:5432
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: root
                    POSTGRES_DB: klickbee-cms
        env:
            DATABASE_URL: "postgres://postgres:root@localhost:5432/klickbee-cms"
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 22
                    cache: npm

            -   name: Install dependencies
                run: npm ci

            -   name: Build with linting
                run: npm run build
