name: CI

on:
  pull_request:

jobs:
  format:
    name: Format
    uses: ./.github/workflows/fmt.yml

  build:
    needs: format
    name: Build
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    name: Test
    uses: ./.github/workflows/test.yml

  security:
    needs: build
    name: Security
    uses: ./.github/workflows/security.yml
    permissions:
      contents: read
      security-events: write
      actions: read
