name: CI

on:
  pull_request:

jobs:
  format:
    name: Check code format
    uses: ./.github/workflows/format.yml

  build:
    needs: format
    name: Build project
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    name: Run tests
    uses: ./.github/workflows/test.yml
